#!/usr/bin/python3

import sys
import os
import time

files = sys.argv[1:]
#commit_note = sys.argv[1]

for i in files:
	os.system("git add {}".format(i))

commit_note = input("Name or note to add to your website? ")

if commit_note == '':
	if len(files) == 1:
		os.system("git commit -am '{}'".format('update ' + files[0]))

	elif len(files) == 2:
		os.system("git commit -am '{}'".format("update {0} and {1}".format(files[0], files[1])))
	else:
		os.system("git commit -a")
else:
	os.system("git commit -am '{}'".format(commit_note))

print(commit_note)
print('\nIn a moment it will ask for a username and password. Please enter (without speech marks):\nusername: "MozFest2019"\npassword: "welovemozfest19"\nThanks! :)\n')
time.sleep(1)
os.system("git push -u origin master")
